server:
  port: 8080
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #NACOS nacos.core.auth.enabled=true开启认证时候使用
        username: nacos
        password: nacos
